<?php

/**
 * @file
 * Allows user with proper privileges to exclude nodes when submitting index to search api.
 */

require_once 'includes/SearchApiExcludeSomeNodes.php';

/**
 * Implements hook_search_api_alter_callback_info().
 */
function stanford_search_api_exclude_nodes_search_api_alter_callback_info() {
  // This will appear as an option in the UI of Search API, in the Data alterations section.
  $callbacks['exclude_some_nodes'] = array(
    'name' => t('Exclude some nodes'), 
    'description' => t('Exclude some nodes from being indexed based on one field value: ApacheSolr Index'),
    'class' => 'SearchApiExcludeSomeNodes',
  );
  return $callbacks;
}
