<?php
/**
 * @file
 * Search API Configuration Module Base.
 */

/**
 * Implements hook_block_info().
 */
function stanford_search_api_block_info() {

  /**
   * Default search block.
   */
  $blocks['search_api_search_block'] = array(
    'info' => t('Search Block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  /**
   * Default search block.
   */
  $blocks['search_api_reset_facets_block'] = array(
    'info' => t('Reset Facets Button'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function stanford_search_api_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'search_api_search_block':
      $block['subject'] = t('Search this site');
      $block['content'] = drupal_get_form('stanford_search_api_search_block_form');
      break;

    case 'search_api_reset_facets_block':
      $block['subject'] = "<none>";
      $block['content'] = stanfod_search_api_reset_facets_block();
      break;

  }
  return $block;
}

/**
 * Single fulltext search patch through block for the search sub modules.
 * @param  [type] $form       [description]
 * @param  [type] $form_state [description]
 * @return [type]             [description]
 */
function stanford_search_api_search_block_form($form, &$form_state) {

  $form["#action"] = url("search/content");

  $form['keywords'] = array(
    '#type' => 'textfield',
    '#default_value' => isset($_REQUEST['search_api_views_fulltext']) ? check_plain($_REQUEST["search_api_views_fulltext"]) : "",
    '#attributes' => array(
      'placeholder' => t('Search this site...'),
      'class' => array('input-medium search-query'),
    ),
    '#attached' => array(
      'js' => array(
        drupal_get_path("module", "stanford_search_api") . "/js/stanford_search_api.js",
      )
    )
  );

  $form['search'] = array(
    '#type' => 'image_button',
    '#src' => drupal_get_path('theme', 'open_framework') . '/images/searchbutton.png',
    '#attributes' => array(
      'class' => array('btn-search'),
      'alt' => t("Search"),
    ),
    '#value' => t('Search'),
  );

  return $form;
}

/**
 * [stanfod_search_api_reset_facets_block description]
 * @return [type] [description]
 */
function stanfod_search_api_reset_facets_block() {
  $search = isset($_GET['search_api_views_fulltext']) ? check_plain($_GET['search_api_views_fulltext']) : FALSE;
  $fs = isset($_GET['f']) ? $_GET['f'] : FALSE;

  if (!$search || !is_array($fs)) {
    return FALSE;
  }

  return drupal_get_form('stanford_search_api_reset_facets_block_form');
}

/**
 * [stanford_search_api_reset_facets_block_form description]
 * @param  [type] $form       [description]
 * @param  [type] $form_state [description]
 * @return [type]             [description]
 */
function stanford_search_api_reset_facets_block_form($form, &$form_state) {
  $search = isset($_GET['search_api_views_fulltext']) ? check_plain($_GET['search_api_views_fulltext']) : FALSE;

  $form = array();
  $form['reset_button'] = array(
    '#type' => 'submit',
    '#value' => t("Reset filters"),
    '#attributes' => array('class' => array('btn', 'reset-button')),
  );

  $form['search_value'] = array(
    '#type' => 'value',
    '#value' => $search,
  );

  return $form;

}

/**
 * [stanford_search_api_reset_facets_block_form description]
 * @param  [type] $form        [description]
 * @param  [type] &$form_state [description]
 * @return [type]              [description]
 */
function stanford_search_api_reset_facets_block_form_submit($form, &$form_state) {
  if (!isset($form_state['values']['search_value'])) {
    drupal_set_message("Missing search value", "error");
    return;
  }
  drupal_goto("search/content", array('query' => array("search_api_views_fulltext" => check_plain($form_state['values']['search_value']))));
}

/**
 * Full text submit redirect.
 * @param  [type] $form       [description]
 * @param  [type] $form_state [description]
 * @return [type]             [description]
 */
function stanford_search_api_search_block_form_submit($form, $form_state) {
  $values = $form_state['values'];

  if (isset($values['keywords'])) {
    drupal_goto('search/content', array('query' => array("search_api_views_fulltext" => check_plain($values['keywords']))));
  }

}

/**
 * Implements hook_views_api().
 */
function stanford_search_api_views_api() {
  return array(
    'api' => "3.0",
  );
}

/**
 * Implements hook_preprocess().
 */
function stanford_search_api_preprocess_html(&$vars) {
  $path = current_path();
  if ($path == "search/content") {
    $vars['head_title'] = t("Search") . " | " . variable_get("site_name", "");
  }
}


/**
 * Implements hook_form_alter().
 */
function stanford_search_api_form_alter(&$form, &$form_state, $form_id) {

  // Add the aria role "combobox" to any fulltext search box that has autocomplete.
  if (isset($form["search_api_views_fulltext"]) && isset($form["search_api_views_fulltext"]['#autocomplete_path'])) {
    $form["search_api_views_fulltext"]["#attributes"]["role"] = "combobox";
    $form["search_api_views_fulltext"]["#attached"]['js'][] = drupal_get_path("module", "stanford_search_api") . "/js/stanford_search_api.js";
    if ($form_state['view']->name == 'gotosolr_nodes' && !empty($form_state['input'])) {
      $form["search_api_views_fulltext"]["#attached"]['js'][] = drupal_get_path("module", "stanford_search_api") . "/js/stanford_search_api_result.js";
    }
  }

}
